compiler_type = "mwcc"

[weight_overrides]
perm_commutative = 100
perm_reorder_decls = 120
perm_inline = 80
perm_var_cond_block = 40
perm_temp_for_expr = 30
perm_expand_expr = 20
perm_split_assignment = 15
perm_compound_assignment = 10
perm_ins_block = 10
perm_remove_var = 10
perm_add_sub = 5
perm_inequalities = 5
perm_reorder_stmts = 0
perm_randomize_internal_type = 0
perm_randomize_external_type = 0
perm_randomize_function_type = 0
perm_remove_ast = 0
perm_pad_var_decl = 0
perm_add_mask = 0
perm_xor_zero = 0
perm_mult_zero = 0
perm_dummy_comma_expr = 0
perm_add_self_assignment = 0
perm_empty_stmt = 0
perm_duplicate_assignment = 0
perm_long_chain_assignment = 0
perm_alias_array = 0
